### ISSUE TITLE
割り算のはずが、かけ算になっている(私たち…入れ替わっているー！？)

### ISSUE THREAD

**Issue by Kotan-86** [Kotan-86/test_github#5]
## 操作手順
12÷3を小数点以下そのままで計算したら
解が36になった

## 本来の想定
12÷3を小数点以下そのままで計算したら
4になってほしい

## 操作環境
* OS: Windows
* OSバージョン: Windows 11
* ブラウザ: Chrome
* ブラウザバージョン: 116.0.5845.188

**Comment by KISETU-ggwp** [comment]
入れ替わっているバグですね。
対策としては
計算の関数を見直すことがいいでしょう。
